export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ENABLE_2FA_BEGIN = 'ENABLE_2FA_BEGIN';
export const ENABLE_2FA_SUCCESS = 'ENABLE_2FA_SUCCESS';
export const ENABLE_2FA_FAIL = 'ENABLE_2FA_FAIL';
export const ENABLE_2FA_IDLE = 'ENABLE_2FA_IDLE';

export const DISABLE_2FA_BEGIN = 'DISABLE_2FA_BEGIN';
export const DISABLE_2FA_SUCCESS = 'DISABLE_2FA_SUCCESS';
export const DISABLE_2FA_FAIL = 'DISABLE_2FA_FAIL';
export const DISABLE_2FA_IDLE = 'DISABLE_2FA_IDLE';

export const CHANGE_USER_TFA_STATE = 'CHANGE_USER_TFA_STATE';
export const AUTH_USER_TFA = 'AUTH_USER_TFA';

export const THEME_TOGGLE = 'THEME_TOGGLE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const START_SWAP_IDLE = 'START_SWAP_IDLE';
export const START_SWAP_BEGIN = 'START_SWAP_BEGIN';
export const START_SWAP_SUCCESS = 'START_SWAP_SUCCESS';
export const START_SWAP_FAIL = 'START_SWAP_FAIL';

export const FETCH_OPERATION_IDLE = 'FETCH_OPERATION_IDLE';
export const FETCH_OPERATION_BEGIN = 'FETCH_OPERATION_BEGIN';
export const FETCH_OPERATION_SUCCESS = 'FETCH_OPERATION_SUCCESS';
export const FETCH_OPERATION_FAIL = 'FETCH_OPERATION_FAIL';

export const START_ASSIGN_TX_IDLE = 'START_ASSIGN_TX_IDLE';
export const START_ASSIGN_TX_BEGIN = 'START_ASSIGN_TX_BEGIN';
export const START_ASSIGN_TX_SUCCESS = 'START_ASSIGN_TX_SUCCESS';
export const START_ASSIGN_TX_FAIL = 'START_ASSIGN_TX_FAIL';
